pipeline {
    agent any 
    tools {
        maven "maven3"
    }
    stages {
        stage('Obtenir la version de maven') { 
            steps {
                sh 'mvn --version'
            }
        }
    }
}