pipeline {
    agent any
    tools {
        maven 'maven3'
    }
    stages {
        stage("obtenir la version de maven") {
            steps {
                sh 'mvn --version'
            }
        }
    }
}